spring:
  application:
    name: family-gateway
  cloud:
    gateway:
      routes:
        - id: family-care
          uri: http://localhost:7072
          predicates:
            - Path=/fc/**
        - id: family-authorization
          uri: http://localhost:7073
          predicates:
            - Path=/login/**, /logout/**

server:
  port: 7070

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/