spring:
  application:
    name: family_discovery
server:
  port: 8762

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
#  server:
#    enable-self-preservation: false

# application.properties configuration below.
#eureka.client.registerWithEureka = true
#eureka.client.fetchRegistry = false
#eureka.server.wait-time-in-ms-when-sync-empty= 0
#
#spring.application.name= nirupon-discovery-service
#server.port = 8761